#!/usr/bin/env bash
# Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
#
# SPDX-License-Identifier: MIT

# Compile-only ABI guard between hipFile and rocprofiler-sdk.
#
# The rocprofiler-sdk profiler re-enforces hipFile's dispatch-table ABI with
# its own static_asserts in
#   projects/rocprofiler-sdk/source/lib/rocprofiler-sdk/hipfile/abi.cpp
# When hipFile appends or reorders a hipFileDispatchTable entry without a
# matching update on the profiler side, the mismatch is only discovered once
# the two land together in the TheRock superproject -- the profiler build then
# fails a compile-time check. This script reproduces that exact condition at
# hipFile PR time by compiling the profiler's abi.cpp against hipFile's REAL
# public headers (ROCPROFILER_SDK_USE_SYSTEM_HIPFILE=1), so the break is caught
# where it originates.
#
# It is compile-only: no linking, no runtime, no GPU. It requires a ROCm/HIP
# toolchain (for <hip/hip_runtime_api.h>, pulled in transitively by
# <hipfile.h>) and so is intended to run inside a hipFile CI container.
#
# Usage:
#   ./check-profiler-abi.sh <rocm-systems-root>
#
# <rocm-systems-root> is the monorepo checkout containing both
# projects/hipfile and projects/rocprofiler-sdk. Defaults to the repo root
# inferred from this script's location.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# util/ -> hipfile/ -> projects/ -> repo root
default_root="$(cd "${script_dir}/../../.." && pwd)"

# Canonicalize to an absolute path so later "${repo_root}/projects/..."
# concatenations resolve correctly regardless of the caller's working
# directory (a relative argument would otherwise be resolved against CWD).
repo_root_arg="${1:-${default_root}}"
if ! repo_root="$(cd "${repo_root_arg}" 2>/dev/null && pwd)"; then
    echo "ERROR: rocm-systems root not found or not a directory: ${repo_root_arg}" >&2
    exit 1
fi

hipfile_include="${repo_root}/projects/hipfile/include"
sdk_root="${repo_root}/projects/rocprofiler-sdk"
sdk_source="${sdk_root}/source"
abi_cpp="${sdk_source}/lib/rocprofiler-sdk/hipfile/abi.cpp"

for path in "${hipfile_include}/hipfile-api-trace.h" "${abi_cpp}"; do
    if [[ ! -f "${path}" ]]; then
        echo "ERROR: required file not found: ${path}" >&2
        echo "Ensure both projects/hipfile and projects/rocprofiler-sdk are checked out." >&2
        exit 1
    fi
done

: "${CXX:=g++}"
: "${ROCM_PATH:=/opt/rocm}"

# Several headers (version.h, ext_version.h, ...) are generated by the
# profiler's CMake from .in templates and so are absent from a plain source
# checkout. abi.cpp pulls some of them in (directly and transitively via
# buffer_tracing.h), but the ABI asserts do not use anything they define, so
# bare stubs are sufficient to let the translation unit parse. Generate a stub
# for every "<name>.h.in" at its matching "<name>.h" path -- deriving the set
# from the tree keeps this robust if the SDK adds another generated header. The
# stub dir is placed first on the include path so the stubs take precedence over
# any stale installed copies under ${ROCM_PATH}.
stub_dir="$(mktemp -d)"
trap 'rm -rf "${stub_dir}"' EXIT
while IFS= read -r -d '' template; do
    rel="${template#"${sdk_source}/include/"}"  # e.g. rocprofiler-sdk/version.h.in
    stub="${stub_dir}/${rel%.in}"               # e.g. <stub_dir>/rocprofiler-sdk/version.h
    mkdir -p "$(dirname "${stub}")"
    printf '#pragma once\n' > "${stub}"
done < <(find "${sdk_source}/include" -name '*.h.in' -print0)

echo "Compiling profiler ABI checks against hipFile's real headers..."
echo "  CXX=${CXX}  ROCM_PATH=${ROCM_PATH}"

# Notes on the flags:
#   -fsyntax-only                        parse + semantic checks (incl.
#                                        static_asserts), no codegen/link
#   ROCPROFILER_SDK_USE_SYSTEM_HIPFILE=1 force abi.cpp to include hipFile's real
#                                        <hipfile-api-trace.h>/<hipfile.h>
#                                        instead of the profiler's vendored copy
#   ROCPROFILER_CI=1                     enable the profiler's stricter CI-only
#                                        ABI asserts (see lib/common/abi.hpp)
#   __HIP_PLATFORM_AMD__                 required by the HIP headers hipfile.h
#                                        transitively includes
"${CXX}" -std=c++17 -fsyntax-only \
    -D__HIP_PLATFORM_AMD__ \
    -DROCPROFILER_SDK_USE_SYSTEM_HIPFILE=1 \
    -DROCPROFILER_CI=1 \
    -I "${stub_dir}" \
    -I "${sdk_source}" \
    -I "${sdk_source}/include" \
    -I "${sdk_source}/lib" \
    -I "${hipfile_include}" \
    -I "${ROCM_PATH}/include" \
    "${abi_cpp}"

echo "OK: profiler ABI checks are consistent with the hipFile dispatch table."
