// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#pragma once

#include "rocjitsu/isa/arch/amdgpu/gfx1250/isa.h"
#include "rocjitsu/isa/execution_backend.h"

namespace rocjitsu {
namespace gfx1250 {

const IsaExecutionBackend &execution_backend();

} // namespace gfx1250
} // namespace rocjitsu
