// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/gfx1250/sopc.h"
#include "util/except.h"

namespace rocjitsu {
namespace gfx1250 {

SCmpEqI32Sopc::SCmpEqI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_eq_i32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(91)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpLgI32Sopc::SCmpLgI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lg_i32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(92)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpGtI32Sopc::SCmpGtI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_gt_i32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(93)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpGeI32Sopc::SCmpGeI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ge_i32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(94)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpLtI32Sopc::SCmpLtI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lt_i32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(95)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpLeI32Sopc::SCmpLeI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_le_i32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(96)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpEqU32Sopc::SCmpEqU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_eq_u32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(97)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpLgU32Sopc::SCmpLgU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lg_u32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(98)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpGtU32Sopc::SCmpGtU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_gt_u32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(99)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpGeU32Sopc::SCmpGeU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ge_u32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(100)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpLtU32Sopc::SCmpLtU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lt_u32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(101)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpLeU32Sopc::SCmpLeU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_le_u32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(102)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SBitcmp0B32Sopc::SBitcmp0B32Sopc(const MachineInst *inst)
    : Sopc("s_bitcmp0_b32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(103)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SBitcmp1B32Sopc::SBitcmp1B32Sopc(const MachineInst *inst)
    : Sopc("s_bitcmp1_b32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(104)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SBitcmp0B64Sopc::SBitcmp0B64Sopc(const MachineInst *inst)
    : Sopc("s_bitcmp0_b64", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(105)),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SBitcmp1B64Sopc::SBitcmp1B64Sopc(const MachineInst *inst)
    : Sopc("s_bitcmp1_b64", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(106)),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpEqU64Sopc::SCmpEqU64Sopc(const MachineInst *inst)
    : Sopc("s_cmp_eq_u64", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(107)),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpLgU64Sopc::SCmpLgU64Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lg_u64", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(108)),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpLtF32Sopc::SCmpLtF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lt_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(109)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpLtF16Sopc::SCmpLtF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lt_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(110)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpEqF32Sopc::SCmpEqF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_eq_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(111)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpEqF16Sopc::SCmpEqF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_eq_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(112)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpLeF32Sopc::SCmpLeF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_le_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(113)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpLeF16Sopc::SCmpLeF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_le_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(114)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpGtF32Sopc::SCmpGtF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_gt_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(115)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpGtF16Sopc::SCmpGtF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_gt_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(116)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpLgF32Sopc::SCmpLgF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lg_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(117)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpLgF16Sopc::SCmpLgF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lg_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(118)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpGeF32Sopc::SCmpGeF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ge_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(119)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpGeF16Sopc::SCmpGeF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ge_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(120)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpOF32Sopc::SCmpOF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_o_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(121)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpOF16Sopc::SCmpOF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_o_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(122)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpUF32Sopc::SCmpUF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_u_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(123)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpUF16Sopc::SCmpUF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_u_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(124)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpNgeF32Sopc::SCmpNgeF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nge_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(125)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpNgeF16Sopc::SCmpNgeF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nge_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(126)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpNlgF32Sopc::SCmpNlgF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nlg_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(127)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpNlgF16Sopc::SCmpNlgF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nlg_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(128)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpNgtF32Sopc::SCmpNgtF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ngt_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(129)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpNgtF16Sopc::SCmpNgtF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ngt_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(130)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpNleF32Sopc::SCmpNleF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nle_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(131)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpNleF16Sopc::SCmpNleF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nle_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(132)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpNeqF32Sopc::SCmpNeqF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_neq_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(133)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpNeqF16Sopc::SCmpNeqF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_neq_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(134)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpNltF32Sopc::SCmpNltF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nlt_f32", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(135)),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

SCmpNltF16Sopc::SCmpNltF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nlt_f16", reinterpret_cast<const OpEncoding *>(inst), selected_exec_fn(136)),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1),
      scc(1, OperandType::OPR_SSRC_SPECIAL_SCC, 253) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  dst_operands_[0] = &scc;
  num_src_ = 2;
  num_dst_ = 1;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 =
        Operand(16, OperandType::OPR_SIMM32,
                static_cast<int>((
                    reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32 & 0xFFFFu)));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  scc.apply_fieldless_caps(false, false, false);
}

} // namespace gfx1250
} // namespace rocjitsu
