// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#ifndef ROCJITSU_ISA_ARCH_AMDGPU_GFX1250_VBUFFER_H_
#define ROCJITSU_ISA_ARCH_AMDGPU_GFX1250_VBUFFER_H_

#include "rocjitsu/isa/arch/amdgpu/gfx1250/encodings.h"
#include "rocjitsu/isa/arch/amdgpu/gfx1250/isa.h"
#include "rocjitsu/isa/arch/amdgpu/gfx1250/operand.h"

namespace rocjitsu {
namespace gfx1250 {

class BufferLoadU8Vbuffer : public Vbuffer {
public:
  BufferLoadU8Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferLoadI8Vbuffer : public Vbuffer {
public:
  BufferLoadI8Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferLoadU16Vbuffer : public Vbuffer {
public:
  BufferLoadU16Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferLoadI16Vbuffer : public Vbuffer {
public:
  BufferLoadI16Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferLoadB32Vbuffer : public Vbuffer {
public:
  BufferLoadB32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferLoadB64Vbuffer : public Vbuffer {
public:
  BufferLoadB64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferLoadB96Vbuffer : public Vbuffer {
public:
  BufferLoadB96Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferLoadB128Vbuffer : public Vbuffer {
public:
  BufferLoadB128Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferStoreB8Vbuffer : public Vbuffer {
public:
  BufferStoreB8Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferStoreB16Vbuffer : public Vbuffer {
public:
  BufferStoreB16Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferStoreB32Vbuffer : public Vbuffer {
public:
  BufferStoreB32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferStoreB64Vbuffer : public Vbuffer {
public:
  BufferStoreB64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferStoreB96Vbuffer : public Vbuffer {
public:
  BufferStoreB96Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferStoreB128Vbuffer : public Vbuffer {
public:
  BufferStoreB128Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferLoadD16U8Vbuffer : public Vbuffer {
public:
  BufferLoadD16U8Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferLoadD16I8Vbuffer : public Vbuffer {
public:
  BufferLoadD16I8Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferLoadD16B16Vbuffer : public Vbuffer {
public:
  BufferLoadD16B16Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferLoadD16HiU8Vbuffer : public Vbuffer {
public:
  BufferLoadD16HiU8Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferLoadD16HiI8Vbuffer : public Vbuffer {
public:
  BufferLoadD16HiI8Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferLoadD16HiB16Vbuffer : public Vbuffer {
public:
  BufferLoadD16HiB16Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferStoreD16HiB8Vbuffer : public Vbuffer {
public:
  BufferStoreD16HiB8Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferStoreD16HiB16Vbuffer : public Vbuffer {
public:
  BufferStoreD16HiB16Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
};

class BufferAtomicSwapB32Vbuffer : public Vbuffer {
public:
  BufferAtomicSwapB32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicCmpswapB32Vbuffer : public Vbuffer {
public:
  BufferAtomicCmpswapB32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vdata_return;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicAddU32Vbuffer : public Vbuffer {
public:
  BufferAtomicAddU32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicSubU32Vbuffer : public Vbuffer {
public:
  BufferAtomicSubU32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicSubClampU32Vbuffer : public Vbuffer {
public:
  BufferAtomicSubClampU32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicMinI32Vbuffer : public Vbuffer {
public:
  BufferAtomicMinI32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicMinU32Vbuffer : public Vbuffer {
public:
  BufferAtomicMinU32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicMaxI32Vbuffer : public Vbuffer {
public:
  BufferAtomicMaxI32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicMaxU32Vbuffer : public Vbuffer {
public:
  BufferAtomicMaxU32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicAndB32Vbuffer : public Vbuffer {
public:
  BufferAtomicAndB32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicOrB32Vbuffer : public Vbuffer {
public:
  BufferAtomicOrB32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicXorB32Vbuffer : public Vbuffer {
public:
  BufferAtomicXorB32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicIncU32Vbuffer : public Vbuffer {
public:
  BufferAtomicIncU32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicDecU32Vbuffer : public Vbuffer {
public:
  BufferAtomicDecU32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicSwapB64Vbuffer : public Vbuffer {
public:
  BufferAtomicSwapB64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicCmpswapB64Vbuffer : public Vbuffer {
public:
  BufferAtomicCmpswapB64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vdata_return;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicAddU64Vbuffer : public Vbuffer {
public:
  BufferAtomicAddU64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicSubU64Vbuffer : public Vbuffer {
public:
  BufferAtomicSubU64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicMinI64Vbuffer : public Vbuffer {
public:
  BufferAtomicMinI64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicMinU64Vbuffer : public Vbuffer {
public:
  BufferAtomicMinU64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicMaxI64Vbuffer : public Vbuffer {
public:
  BufferAtomicMaxI64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicMaxU64Vbuffer : public Vbuffer {
public:
  BufferAtomicMaxU64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicAndB64Vbuffer : public Vbuffer {
public:
  BufferAtomicAndB64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicOrB64Vbuffer : public Vbuffer {
public:
  BufferAtomicOrB64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicXorB64Vbuffer : public Vbuffer {
public:
  BufferAtomicXorB64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicIncU64Vbuffer : public Vbuffer {
public:
  BufferAtomicIncU64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicDecU64Vbuffer : public Vbuffer {
public:
  BufferAtomicDecU64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicCondSubU32Vbuffer : public Vbuffer {
public:
  BufferAtomicCondSubU32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicMinNumF32Vbuffer : public Vbuffer {
public:
  BufferAtomicMinNumF32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicMaxNumF32Vbuffer : public Vbuffer {
public:
  BufferAtomicMaxNumF32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicAddF64Vbuffer : public Vbuffer {
public:
  BufferAtomicAddF64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicAddF32Vbuffer : public Vbuffer {
public:
  BufferAtomicAddF32Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicPkAddF16Vbuffer : public Vbuffer {
public:
  BufferAtomicPkAddF16Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicPkAddBf16Vbuffer : public Vbuffer {
public:
  BufferAtomicPkAddBf16Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicMinNumF64Vbuffer : public Vbuffer {
public:
  BufferAtomicMinNumF64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

class BufferAtomicMaxNumF64Vbuffer : public Vbuffer {
public:
  BufferAtomicMaxNumF64Vbuffer(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand rsrc;
  Operand soffset;
  Operand gpumem;
  Operand gpumem_in;
};

} // namespace gfx1250
} // namespace rocjitsu

#endif // ROCJITSU_ISA_ARCH_AMDGPU_GFX1250_VBUFFER_H_
