// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#ifndef ROCJITSU_ISA_ARCH_AMDGPU_GFX1250_VGLOBAL_H_
#define ROCJITSU_ISA_ARCH_AMDGPU_GFX1250_VGLOBAL_H_

#include "rocjitsu/isa/arch/amdgpu/gfx1250/encodings.h"
#include "rocjitsu/isa/arch/amdgpu/gfx1250/isa.h"
#include "rocjitsu/isa/arch/amdgpu/gfx1250/operand.h"

namespace rocjitsu {
namespace gfx1250 {

class GlobalLoadU8Vglobal : public Vglobal {
public:
  GlobalLoadU8Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadI8Vglobal : public Vglobal {
public:
  GlobalLoadI8Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadU16Vglobal : public Vglobal {
public:
  GlobalLoadU16Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadI16Vglobal : public Vglobal {
public:
  GlobalLoadI16Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadB32Vglobal : public Vglobal {
public:
  GlobalLoadB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadB64Vglobal : public Vglobal {
public:
  GlobalLoadB64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadB96Vglobal : public Vglobal {
public:
  GlobalLoadB96Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadB128Vglobal : public Vglobal {
public:
  GlobalLoadB128Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalStoreB8Vglobal : public Vglobal {
public:
  GlobalStoreB8Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
};

class GlobalStoreB16Vglobal : public Vglobal {
public:
  GlobalStoreB16Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
};

class GlobalStoreB32Vglobal : public Vglobal {
public:
  GlobalStoreB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
};

class GlobalStoreB64Vglobal : public Vglobal {
public:
  GlobalStoreB64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
};

class GlobalStoreB96Vglobal : public Vglobal {
public:
  GlobalStoreB96Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
};

class GlobalStoreB128Vglobal : public Vglobal {
public:
  GlobalStoreB128Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadD16U8Vglobal : public Vglobal {
public:
  GlobalLoadD16U8Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadD16I8Vglobal : public Vglobal {
public:
  GlobalLoadD16I8Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadD16B16Vglobal : public Vglobal {
public:
  GlobalLoadD16B16Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadD16HiU8Vglobal : public Vglobal {
public:
  GlobalLoadD16HiU8Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadD16HiI8Vglobal : public Vglobal {
public:
  GlobalLoadD16HiI8Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadD16HiB16Vglobal : public Vglobal {
public:
  GlobalLoadD16HiB16Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalStoreD16HiB8Vglobal : public Vglobal {
public:
  GlobalStoreD16HiB8Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
};

class GlobalStoreD16HiB16Vglobal : public Vglobal {
public:
  GlobalStoreD16HiB16Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadAddtidB32Vglobal : public Vglobal {
public:
  GlobalLoadAddtidB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand saddr;
  Operand gpumem;
};

class GlobalStoreAddtidB32Vglobal : public Vglobal {
public:
  GlobalStoreAddtidB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
};

class GlobalInvVglobal : public Vglobal {
public:
  GlobalInvVglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
};

class GlobalWbVglobal : public Vglobal {
public:
  GlobalWbVglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
};

class GlobalAtomicSwapB32Vglobal : public Vglobal {
public:
  GlobalAtomicSwapB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicCmpswapB32Vglobal : public Vglobal {
public:
  GlobalAtomicCmpswapB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicAddU32Vglobal : public Vglobal {
public:
  GlobalAtomicAddU32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicSubU32Vglobal : public Vglobal {
public:
  GlobalAtomicSubU32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicSubClampU32Vglobal : public Vglobal {
public:
  GlobalAtomicSubClampU32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicMinI32Vglobal : public Vglobal {
public:
  GlobalAtomicMinI32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicMinU32Vglobal : public Vglobal {
public:
  GlobalAtomicMinU32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicMaxI32Vglobal : public Vglobal {
public:
  GlobalAtomicMaxI32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicMaxU32Vglobal : public Vglobal {
public:
  GlobalAtomicMaxU32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicAndB32Vglobal : public Vglobal {
public:
  GlobalAtomicAndB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicOrB32Vglobal : public Vglobal {
public:
  GlobalAtomicOrB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicXorB32Vglobal : public Vglobal {
public:
  GlobalAtomicXorB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicIncU32Vglobal : public Vglobal {
public:
  GlobalAtomicIncU32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicDecU32Vglobal : public Vglobal {
public:
  GlobalAtomicDecU32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicSwapB64Vglobal : public Vglobal {
public:
  GlobalAtomicSwapB64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicCmpswapB64Vglobal : public Vglobal {
public:
  GlobalAtomicCmpswapB64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicAddU64Vglobal : public Vglobal {
public:
  GlobalAtomicAddU64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicSubU64Vglobal : public Vglobal {
public:
  GlobalAtomicSubU64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicMinI64Vglobal : public Vglobal {
public:
  GlobalAtomicMinI64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicMinU64Vglobal : public Vglobal {
public:
  GlobalAtomicMinU64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicMaxI64Vglobal : public Vglobal {
public:
  GlobalAtomicMaxI64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicMaxU64Vglobal : public Vglobal {
public:
  GlobalAtomicMaxU64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicAndB64Vglobal : public Vglobal {
public:
  GlobalAtomicAndB64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicOrB64Vglobal : public Vglobal {
public:
  GlobalAtomicOrB64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicXorB64Vglobal : public Vglobal {
public:
  GlobalAtomicXorB64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicIncU64Vglobal : public Vglobal {
public:
  GlobalAtomicIncU64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicDecU64Vglobal : public Vglobal {
public:
  GlobalAtomicDecU64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalWbinvVglobal : public Vglobal {
public:
  GlobalWbinvVglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
};

class GlobalAtomicCondSubU32Vglobal : public Vglobal {
public:
  GlobalAtomicCondSubU32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicMinNumF32Vglobal : public Vglobal {
public:
  GlobalAtomicMinNumF32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicMaxNumF32Vglobal : public Vglobal {
public:
  GlobalAtomicMaxNumF32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalLoadBlockVglobal : public Vglobal {
public:
  GlobalLoadBlockVglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
  Operand m0;
};

class GlobalStoreBlockVglobal : public Vglobal {
public:
  GlobalStoreBlockVglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand m0;
};

class GlobalAtomicAddF64Vglobal : public Vglobal {
public:
  GlobalAtomicAddF64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicAddF32Vglobal : public Vglobal {
public:
  GlobalAtomicAddF32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalLoadTr16B128Vglobal : public Vglobal {
public:
  GlobalLoadTr16B128Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadTr8B64Vglobal : public Vglobal {
public:
  GlobalLoadTr8B64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalAtomicPkAddF16Vglobal : public Vglobal {
public:
  GlobalAtomicPkAddF16Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicPkAddBf16Vglobal : public Vglobal {
public:
  GlobalAtomicPkAddBf16Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicMinNumF64Vglobal : public Vglobal {
public:
  GlobalAtomicMinNumF64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalAtomicMaxNumF64Vglobal : public Vglobal {
public:
  GlobalAtomicMaxNumF64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand gpumem_in;
};

class GlobalPrefetchB8Vglobal : public Vglobal {
public:
  GlobalPrefetchB8Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadAsyncToLdsB8Vglobal : public Vglobal {
public:
  GlobalLoadAsyncToLdsB8Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand dsmem;
  Operand gpumem;
};

class GlobalLoadAsyncToLdsB32Vglobal : public Vglobal {
public:
  GlobalLoadAsyncToLdsB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand dsmem;
  Operand gpumem;
};

class GlobalLoadAsyncToLdsB64Vglobal : public Vglobal {
public:
  GlobalLoadAsyncToLdsB64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand dsmem;
  Operand gpumem;
};

class GlobalLoadAsyncToLdsB128Vglobal : public Vglobal {
public:
  GlobalLoadAsyncToLdsB128Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand dsmem;
  Operand gpumem;
};

class GlobalStoreAsyncFromLdsB8Vglobal : public Vglobal {
public:
  GlobalStoreAsyncFromLdsB8Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand dsmem;
};

class GlobalStoreAsyncFromLdsB32Vglobal : public Vglobal {
public:
  GlobalStoreAsyncFromLdsB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand dsmem;
};

class GlobalStoreAsyncFromLdsB64Vglobal : public Vglobal {
public:
  GlobalStoreAsyncFromLdsB64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand dsmem;
};

class GlobalStoreAsyncFromLdsB128Vglobal : public Vglobal {
public:
  GlobalStoreAsyncFromLdsB128Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
  Operand saddr;
  Operand gpumem;
  Operand dsmem;
};

class ClusterLoadB32Vglobal : public Vglobal {
public:
  ClusterLoadB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
  Operand m0;
};

class ClusterLoadB64Vglobal : public Vglobal {
public:
  ClusterLoadB64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
  Operand m0;
};

class ClusterLoadB128Vglobal : public Vglobal {
public:
  ClusterLoadB128Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
  Operand m0;
};

class ClusterLoadAsyncToLdsB8Vglobal : public Vglobal {
public:
  ClusterLoadAsyncToLdsB8Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand dsmem;
  Operand gpumem;
  Operand m0;
};

class ClusterLoadAsyncToLdsB32Vglobal : public Vglobal {
public:
  ClusterLoadAsyncToLdsB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand dsmem;
  Operand gpumem;
  Operand m0;
};

class ClusterLoadAsyncToLdsB64Vglobal : public Vglobal {
public:
  ClusterLoadAsyncToLdsB64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand dsmem;
  Operand gpumem;
  Operand m0;
};

class ClusterLoadAsyncToLdsB128Vglobal : public Vglobal {
public:
  ClusterLoadAsyncToLdsB128Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand dsmem;
  Operand gpumem;
  Operand m0;
};

class GlobalLoadMonitorB32Vglobal : public Vglobal {
public:
  GlobalLoadMonitorB32Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadMonitorB64Vglobal : public Vglobal {
public:
  GlobalLoadMonitorB64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadMonitorB128Vglobal : public Vglobal {
public:
  GlobalLoadMonitorB128Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadTr4B64Vglobal : public Vglobal {
public:
  GlobalLoadTr4B64Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

class GlobalLoadTr6B96Vglobal : public Vglobal {
public:
  GlobalLoadTr6B96Vglobal(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand saddr;
  Operand gpumem;
};

} // namespace gfx1250
} // namespace rocjitsu

#endif // ROCJITSU_ISA_ARCH_AMDGPU_GFX1250_VGLOBAL_H_
