// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/gfx1250/vop2.h"
#include "rocjitsu/isa/arch/amdgpu/shared/dpp_sdwa_ops.h"
#include "rocjitsu/isa/arch/amdgpu/shared/execute_shared.h"
#include "rocjitsu/isa/arch/amdgpu/shared/transcendental.h"
#include "rocjitsu/vm/amdgpu/register_access.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace gfx1250 {

void VCndmaskB32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cndmask_b32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VAddF64Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_add_f64_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VAddF32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_add_f32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VSubF32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_sub_f32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VSubrevF32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_subrev_f32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMulF64Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_mul_f64_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMulDx9ZeroF32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_mul_dx9_zero_f32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMulF32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_mul_f32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMulI32I24Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_mul_i32_i24_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMulHiI32I24Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_mul_hi_i32_i24_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMulU32U24Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_mul_u32_u24_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMulHiU32U24Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_mul_hi_u32_u24_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMinNumF64Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_min_num_f64_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMaxNumF64Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_max_num_f64_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMinI32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_min_i32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMaxI32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_max_i32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMinU32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_min_u32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMaxU32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_max_u32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMinNumF32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_min_num_f32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMaxNumF32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_max_num_f32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VFmacF64Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_fmac_f64_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VLshlrevB32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_lshlrev_b32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VLshrrevB32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_lshrrev_b32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VAshrrevI32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_ashrrev_i32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VAndB32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_and_b32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VOrB32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_or_b32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VXorB32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_xor_b32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VXnorB32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_xnor_b32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VLshlrevB64Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_lshlrev_b64_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VAddCoCiU32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_add_co_ci_u32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VSubCoCiU32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_sub_co_ci_u32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VSubrevCoCiU32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_subrev_co_ci_u32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VFmamkF64Vop2::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

void VFmaakF64Vop2::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

void VAddNcU32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_add_nc_u32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VSubNcU32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_sub_nc_u32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VSubrevNcU32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_subrev_nc_u32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VAddNcU64Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = amdgpu::dpp::execution_lane_mask(*this, wf);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    amdgpu::sdwa::write_lane64<false>(
        *this, wf, vdst, lane,
        (static_cast<uint64_t>(amdgpu::RegisterAccess(wf).read_lane64(src0, lane)) +
         static_cast<uint64_t>(amdgpu::RegisterAccess(wf).read_lane64(vsrc1, lane))));
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VSubNcU64Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = amdgpu::dpp::execution_lane_mask(*this, wf);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    amdgpu::sdwa::write_lane64<false>(
        *this, wf, vdst, lane,
        (static_cast<uint64_t>(amdgpu::RegisterAccess(wf).read_lane64(src0, lane)) -
         static_cast<uint64_t>(amdgpu::RegisterAccess(wf).read_lane64(vsrc1, lane))));
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMulU64Vop2::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t exec = wf.exec();
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    amdgpu::sdwa::write_lane64<false>(
        *this, wf, vdst, lane,
        (static_cast<uint64_t>(amdgpu::RegisterAccess(wf).read_lane64(src0, lane)) *
         static_cast<uint64_t>(amdgpu::RegisterAccess(wf).read_lane64(vsrc1, lane))));
  }
}

void VFmacF32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_fmac_f32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VFmamkF32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t exec = wf.exec();
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    float s0 = std::bit_cast<float>(amdgpu::RegisterAccess(wf).read_lane(src0, lane));
    float k = std::bit_cast<float>(literal.encoding_value_);
    float s2 = std::bit_cast<float>(amdgpu::RegisterAccess(wf).read_lane(vsrc1, lane));
    amdgpu::sdwa::write_lane<true>(*this, wf, vdst, lane,
                                   std::bit_cast<uint32_t>(std::fma(s0, k, s2)));
  }
}

void VFmaakF32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t exec = wf.exec();
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    float s0 = std::bit_cast<float>(amdgpu::RegisterAccess(wf).read_lane(src0, lane));
    float s1 = std::bit_cast<float>(amdgpu::RegisterAccess(wf).read_lane(vsrc1, lane));
    float k = std::bit_cast<float>(literal.encoding_value_);
    amdgpu::sdwa::write_lane<true>(*this, wf, vdst, lane,
                                   std::bit_cast<uint32_t>(std::fma(s0, s1, k)));
  }
}

void VCvtPkRtzF16F32Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cvt_pk_rtz_f16_f32_vop2(*this, wf);
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMinNumF16Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = amdgpu::dpp::execution_lane_mask(*this, wf);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    amdgpu::sdwa::write_lane<true>(
        *this, wf, vdst, lane,
        util::f32_to_f16_mode(std::fmin(util::f16_to_f32(static_cast<uint16_t>(
                                            amdgpu::RegisterAccess(wf).read_lane(src0, lane))),
                                        util::f16_to_f32(static_cast<uint16_t>(
                                            amdgpu::RegisterAccess(wf).read_lane(vsrc1, lane)))),
                              wf.fp16_ovfl()));
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMaxNumF16Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = amdgpu::dpp::execution_lane_mask(*this, wf);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    amdgpu::sdwa::write_lane<true>(
        *this, wf, vdst, lane,
        util::f32_to_f16_mode(std::fmax(util::f16_to_f32(static_cast<uint16_t>(
                                            amdgpu::RegisterAccess(wf).read_lane(src0, lane))),
                                        util::f16_to_f32(static_cast<uint16_t>(
                                            amdgpu::RegisterAccess(wf).read_lane(vsrc1, lane)))),
                              wf.fp16_ovfl()));
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VAddF16Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = amdgpu::dpp::execution_lane_mask(*this, wf);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    amdgpu::sdwa::write_lane<true>(
        *this, wf, vdst, lane,
        util::f32_to_f16_mode((util::f16_to_f32(static_cast<uint16_t>(
                                   amdgpu::RegisterAccess(wf).read_lane(src0, lane))) +
                               util::f16_to_f32(static_cast<uint16_t>(
                                   amdgpu::RegisterAccess(wf).read_lane(vsrc1, lane)))),
                              wf.fp16_ovfl()));
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VSubF16Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = amdgpu::dpp::execution_lane_mask(*this, wf);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    amdgpu::sdwa::write_lane<true>(
        *this, wf, vdst, lane,
        util::f32_to_f16_mode((util::f16_to_f32(static_cast<uint16_t>(
                                   amdgpu::RegisterAccess(wf).read_lane(src0, lane))) -
                               util::f16_to_f32(static_cast<uint16_t>(
                                   amdgpu::RegisterAccess(wf).read_lane(vsrc1, lane)))),
                              wf.fp16_ovfl()));
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VSubrevF16Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = amdgpu::dpp::execution_lane_mask(*this, wf);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    amdgpu::sdwa::write_lane<true>(
        *this, wf, vdst, lane,
        util::f32_to_f16_mode((util::f16_to_f32(static_cast<uint16_t>(
                                   amdgpu::RegisterAccess(wf).read_lane(vsrc1, lane))) -
                               util::f16_to_f32(static_cast<uint16_t>(
                                   amdgpu::RegisterAccess(wf).read_lane(src0, lane)))),
                              wf.fp16_ovfl()));
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VMulF16Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = amdgpu::dpp::execution_lane_mask(*this, wf);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    amdgpu::sdwa::write_lane<true>(
        *this, wf, vdst, lane,
        util::f32_to_f16_mode((util::f16_to_f32(static_cast<uint16_t>(
                                   amdgpu::RegisterAccess(wf).read_lane(src0, lane))) *
                               util::f16_to_f32(static_cast<uint16_t>(
                                   amdgpu::RegisterAccess(wf).read_lane(vsrc1, lane)))),
                              wf.fp16_ovfl()));
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VFmacF16Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = amdgpu::dpp::execution_lane_mask(*this, wf);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    amdgpu::sdwa::write_lane<true>(
        *this, wf, vdst, lane,
        util::f32_to_f16_mode(std::fma(util::f16_to_f32(static_cast<uint16_t>(
                                           amdgpu::RegisterAccess(wf).read_lane(src0, lane))),
                                       util::f16_to_f32(static_cast<uint16_t>(
                                           amdgpu::RegisterAccess(wf).read_lane(vsrc1, lane))),
                                       util::f16_to_f32(static_cast<uint16_t>(
                                           amdgpu::RegisterAccess(wf).read_lane(vdst, lane)))),
                              wf.fp16_ovfl()));
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VFmamkF16Vop2::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t exec = wf.exec();
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    float s0 =
        util::f16_to_f32(static_cast<uint16_t>(amdgpu::RegisterAccess(wf).read_lane(src0, lane)));
    float k = util::f16_to_f32(static_cast<uint16_t>(literal.encoding_value_));
    float s2 =
        util::f16_to_f32(static_cast<uint16_t>(amdgpu::RegisterAccess(wf).read_lane(vsrc1, lane)));
    amdgpu::sdwa::write_lane<true>(*this, wf, vdst, lane,
                                   util::f32_to_f16_mode(std::fma(s0, k, s2), wf.fp16_ovfl()));
  }
}

void VFmaakF16Vop2::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t exec = wf.exec();
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    float s0 =
        util::f16_to_f32(static_cast<uint16_t>(amdgpu::RegisterAccess(wf).read_lane(src0, lane)));
    float s1 =
        util::f16_to_f32(static_cast<uint16_t>(amdgpu::RegisterAccess(wf).read_lane(vsrc1, lane)));
    float k = util::f16_to_f32(static_cast<uint16_t>(literal.encoding_value_));
    amdgpu::sdwa::write_lane<true>(*this, wf, vdst, lane,
                                   util::f32_to_f16_mode(std::fma(s0, s1, k), wf.fp16_ovfl()));
  }
}

void VLdexpF16Vop2::execute_impl(amdgpu::Wavefront &wf) {
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = amdgpu::dpp::execution_lane_mask(*this, wf);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    amdgpu::sdwa::write_lane<true>(
        *this, wf, vdst, lane,
        util::f32_to_f16_mode(std::ldexp(util::f16_to_f32(static_cast<uint16_t>(
                                             amdgpu::RegisterAccess(wf).read_lane(src0, lane))),
                                         static_cast<int32_t>(static_cast<int16_t>(
                                             amdgpu::RegisterAccess(wf).read_lane(vsrc1, lane)))),
                              wf.fp16_ovfl()));
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VPkFmacF16Vop2::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

} // namespace gfx1250
} // namespace rocjitsu
