// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/gfx1250/vopc.h"
#include "rocjitsu/isa/arch/amdgpu/shared/dpp_sdwa_ops.h"
#include "rocjitsu/isa/arch/amdgpu/shared/execute_shared.h"
#include "rocjitsu/isa/arch/amdgpu/shared/transcendental.h"
#include "rocjitsu/vm/amdgpu/register_access.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace gfx1250 {

void VCmpLtF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_lt_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpEqF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_eq_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLeF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_le_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpGtF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_gt_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLgF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_lg_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpGeF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_ge_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpOF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_o_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpUF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_u_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNgeF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_nge_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNlgF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_nlg_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNgtF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_ngt_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNleF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_nle_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNeqF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_neq_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNltF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_nlt_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLtF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_lt_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpEqF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_eq_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLeF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_le_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpGtF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_gt_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLgF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_lg_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpGeF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_ge_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpOF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_o_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpUF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_u_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNgeF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_nge_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNlgF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_nlg_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNgtF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_ngt_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNleF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_nle_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNeqF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_neq_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNltF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_nlt_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLtF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_lt_f64_vopc(*this, wf);
}

void VCmpEqF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_eq_f64_vopc(*this, wf);
}

void VCmpLeF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_le_f64_vopc(*this, wf);
}

void VCmpGtF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_gt_f64_vopc(*this, wf);
}

void VCmpLgF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_lg_f64_vopc(*this, wf);
}

void VCmpGeF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_ge_f64_vopc(*this, wf);
}

void VCmpOF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_o_f64_vopc(*this, wf);
}

void VCmpUF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_u_f64_vopc(*this, wf);
}

void VCmpNgeF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_nge_f64_vopc(*this, wf);
}

void VCmpNlgF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_nlg_f64_vopc(*this, wf);
}

void VCmpNgtF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_ngt_f64_vopc(*this, wf);
}

void VCmpNleF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_nle_f64_vopc(*this, wf);
}

void VCmpNeqF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_neq_f64_vopc(*this, wf);
}

void VCmpNltF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_nlt_f64_vopc(*this, wf);
}

void VCmpLtI16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_lt_i16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpEqI16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_eq_i16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLeI16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_le_i16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpGtI16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_gt_i16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNeI16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_ne_i16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpGeI16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_ge_i16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLtU16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_lt_u16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpEqU16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_eq_u16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLeU16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_le_u16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpGtU16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_gt_u16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNeU16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_ne_u16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpGeU16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_ge_u16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLtI32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_lt_i32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpEqI32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_eq_i32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLeI32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_le_i32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpGtI32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_gt_i32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNeI32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_ne_i32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpGeI32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_ge_i32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLtU32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_lt_u32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpEqU32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_eq_u32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLeU32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_le_u32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpGtU32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_gt_u32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpNeU32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_ne_u32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpGeU32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_ge_u32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpLtI64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_lt_i64_vopc(*this, wf);
}

void VCmpEqI64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_eq_i64_vopc(*this, wf);
}

void VCmpLeI64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_le_i64_vopc(*this, wf);
}

void VCmpGtI64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_gt_i64_vopc(*this, wf);
}

void VCmpNeI64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_ne_i64_vopc(*this, wf);
}

void VCmpGeI64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_ge_i64_vopc(*this, wf);
}

void VCmpLtU64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_lt_u64_vopc(*this, wf);
}

void VCmpEqU64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_eq_u64_vopc(*this, wf);
}

void VCmpLeU64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_le_u64_vopc(*this, wf);
}

void VCmpGtU64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_gt_u64_vopc(*this, wf);
}

void VCmpNeU64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_ne_u64_vopc(*this, wf);
}

void VCmpGeU64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_ge_u64_vopc(*this, wf);
}

void VCmpClassF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_class_f16_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpClassF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = amdgpu::dpp::dpp_write_mask(wf.wf_size(), dpp_ctrl_, dpp_row_mask_,
                                                  dpp_bank_mask_, dpp_bound_ctrl_);
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_fi_, dpp_src0_, wf);
  if (amdgpu::dpp::is_src_dpp8(inst_.src0))
    amdgpu::dpp::apply_dpp8(src_operands_[0], dpp8_lane_sel_, dpp_fi_, dpp_src0_, wf);
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  amdgpu::execute_v_cmp_class_f32_vopc(*this, wf);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

void VCmpClassF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_v_cmp_class_f64_vopc(*this, wf);
}

} // namespace gfx1250
} // namespace rocjitsu
