// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/gfx1250/vopc.h"
#include "rocjitsu/isa/arch/amdgpu/shared/dpp_sdwa_ops.h"
#include "rocjitsu/isa/arch/amdgpu/shared/execute_shared.h"
#include "rocjitsu/isa/arch/amdgpu/shared/transcendental.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace gfx1250 {

void VCmpxNeU32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t s0 = src0.read_lane(wf, lane);
    uint32_t s1 = vsrc1.read_lane(wf, lane);
    if (s0 != s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxGeU32Vopc::VCmpxGeU32Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_ge_u32_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxGeU32Vopc>()),
      src0(32, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(32, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxGeU32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t s0 = src0.read_lane(wf, lane);
    uint32_t s1 = vsrc1.read_lane(wf, lane);
    if (s0 >= s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxLtI64Vopc::VCmpxLtI64Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_lt_i64_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxLtI64Vopc>()),
      src0(64, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(64, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxLtI64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    int64_t s0 = static_cast<int64_t>(src0.read_lane64(wf, lane));
    int64_t s1 = static_cast<int64_t>(vsrc1.read_lane64(wf, lane));
    if (s0 < s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxEqI64Vopc::VCmpxEqI64Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_eq_i64_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxEqI64Vopc>()),
      src0(64, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(64, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxEqI64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    int64_t s0 = static_cast<int64_t>(src0.read_lane64(wf, lane));
    int64_t s1 = static_cast<int64_t>(vsrc1.read_lane64(wf, lane));
    if (s0 == s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxLeI64Vopc::VCmpxLeI64Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_le_i64_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxLeI64Vopc>()),
      src0(64, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(64, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxLeI64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    int64_t s0 = static_cast<int64_t>(src0.read_lane64(wf, lane));
    int64_t s1 = static_cast<int64_t>(vsrc1.read_lane64(wf, lane));
    if (s0 <= s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxGtI64Vopc::VCmpxGtI64Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_gt_i64_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxGtI64Vopc>()),
      src0(64, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(64, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxGtI64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    int64_t s0 = static_cast<int64_t>(src0.read_lane64(wf, lane));
    int64_t s1 = static_cast<int64_t>(vsrc1.read_lane64(wf, lane));
    if (s0 > s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxNeI64Vopc::VCmpxNeI64Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_ne_i64_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxNeI64Vopc>()),
      src0(64, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(64, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxNeI64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    int64_t s0 = static_cast<int64_t>(src0.read_lane64(wf, lane));
    int64_t s1 = static_cast<int64_t>(vsrc1.read_lane64(wf, lane));
    if (s0 != s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxGeI64Vopc::VCmpxGeI64Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_ge_i64_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxGeI64Vopc>()),
      src0(64, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(64, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxGeI64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    int64_t s0 = static_cast<int64_t>(src0.read_lane64(wf, lane));
    int64_t s1 = static_cast<int64_t>(vsrc1.read_lane64(wf, lane));
    if (s0 >= s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxLtU64Vopc::VCmpxLtU64Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_lt_u64_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxLtU64Vopc>()),
      src0(64, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(64, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxLtU64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint64_t s0 = src0.read_lane64(wf, lane);
    uint64_t s1 = vsrc1.read_lane64(wf, lane);
    if (s0 < s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxEqU64Vopc::VCmpxEqU64Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_eq_u64_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxEqU64Vopc>()),
      src0(64, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(64, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxEqU64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint64_t s0 = src0.read_lane64(wf, lane);
    uint64_t s1 = vsrc1.read_lane64(wf, lane);
    if (s0 == s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxLeU64Vopc::VCmpxLeU64Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_le_u64_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxLeU64Vopc>()),
      src0(64, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(64, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxLeU64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint64_t s0 = src0.read_lane64(wf, lane);
    uint64_t s1 = vsrc1.read_lane64(wf, lane);
    if (s0 <= s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxGtU64Vopc::VCmpxGtU64Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_gt_u64_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxGtU64Vopc>()),
      src0(64, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(64, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxGtU64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint64_t s0 = src0.read_lane64(wf, lane);
    uint64_t s1 = vsrc1.read_lane64(wf, lane);
    if (s0 > s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxNeU64Vopc::VCmpxNeU64Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_ne_u64_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxNeU64Vopc>()),
      src0(64, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(64, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxNeU64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint64_t s0 = src0.read_lane64(wf, lane);
    uint64_t s1 = vsrc1.read_lane64(wf, lane);
    if (s0 != s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxGeU64Vopc::VCmpxGeU64Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_ge_u64_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxGeU64Vopc>()),
      src0(64, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(64, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxGeU64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint64_t s0 = src0.read_lane64(wf, lane);
    uint64_t s1 = vsrc1.read_lane64(wf, lane);
    if (s0 >= s1)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxClassF16Vopc::VCmpxClassF16Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_class_f16_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxClassF16Vopc>()),
      src0(16, OperandType::OPR_SRC,
           static_cast<unsigned short>(reinterpret_cast<const OpEncoding *>(inst)->src0), true),
      vsrc1(16, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(16, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxClassF16Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint16_t s0_raw = static_cast<uint16_t>(src0.read_lane(wf, lane));
    float s0 = util::f16_to_f32(s0_raw);
    uint32_t mask = vsrc1.read_lane(wf, lane);
    bool match = false;
    bool is_f16_nan = ((s0_raw & 0x7C00) == 0x7C00) && ((s0_raw & 0x03FF) != 0);
    if ((mask & 0x001) && is_f16_nan && (s0_raw & 0x0200) == 0)
      match = true;
    if ((mask & 0x002) && is_f16_nan && (s0_raw & 0x0200) != 0)
      match = true;
    if ((mask & 0x004) && std::isinf(s0) && s0 < 0)
      match = true;
    if ((mask & 0x008) && std::isnormal(s0) && s0 < 0)
      match = true;
    if ((mask & 0x010) && !std::isnormal(s0) && !std::isinf(s0) && !std::isnan(s0) && s0 != 0.0f &&
        std::signbit(s0))
      match = true;
    if ((mask & 0x020) && s0 == 0.0f && std::signbit(s0))
      match = true;
    if ((mask & 0x040) && s0 == 0.0f && !std::signbit(s0))
      match = true;
    if ((mask & 0x080) && !std::isnormal(s0) && !std::isinf(s0) && !std::isnan(s0) && s0 != 0.0f &&
        !std::signbit(s0))
      match = true;
    if ((mask & 0x100) && std::isnormal(s0) && s0 > 0)
      match = true;
    if ((mask & 0x200) && std::isinf(s0) && s0 > 0)
      match = true;
    if (match)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxClassF32Vopc::VCmpxClassF32Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_class_f32_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxClassF32Vopc>()),
      src0(32, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(32, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxClassF32Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    float s0 = std::bit_cast<float>(src0.read_lane(wf, lane));
    uint32_t mask = vsrc1.read_lane(wf, lane);
    bool match = false;
    if ((mask & 0x001) && std::isnan(s0) && (std::bit_cast<uint32_t>(s0) & 0x00400000) == 0)
      match = true;
    if ((mask & 0x002) && std::isnan(s0) && (std::bit_cast<uint32_t>(s0) & 0x00400000) != 0)
      match = true;
    if ((mask & 0x004) && std::isinf(s0) && s0 < 0)
      match = true;
    if ((mask & 0x008) && std::isnormal(s0) && s0 < 0)
      match = true;
    if ((mask & 0x010) && !std::isnormal(s0) && !std::isinf(s0) && !std::isnan(s0) && s0 != 0.0f &&
        std::signbit(s0))
      match = true;
    if ((mask & 0x020) && s0 == 0.0f && std::signbit(s0))
      match = true;
    if ((mask & 0x040) && s0 == 0.0f && !std::signbit(s0))
      match = true;
    if ((mask & 0x080) && !std::isnormal(s0) && !std::isinf(s0) && !std::isnan(s0) && s0 != 0.0f &&
        !std::signbit(s0))
      match = true;
    if ((mask & 0x100) && std::isnormal(s0) && s0 > 0)
      match = true;
    if ((mask & 0x200) && std::isinf(s0) && s0 > 0)
      match = true;
    if (match)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

VCmpxClassF64Vopc::VCmpxClassF64Vopc(const MachineInst *inst)
    : Vopc("v_cmpx_class_f64_e32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<VCmpxClassF64Vopc>()),
      src0(64, OperandType::OPR_SRC, reinterpret_cast<const OpEncoding *>(inst)->src0),
      vsrc1(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc1) {
  src_operands_[0] = &src0;
  src_operands_[1] = &vsrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 255)
    src0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const VopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    src0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->src0 == amdgpu::SRC_DPP) {
    auto *dp = reinterpret_cast<const Vop1VopDpp16MachineInst *>(inst);
    src0 = Operand(64, OperandType::OPR_VGPR, dp->vsrc0);
    dpp_ctrl_ = dp->dpp_ctrl;
    dpp_row_mask_ = dp->row_mask;
    dpp_bank_mask_ = dp->bank_mask;
    dpp_bound_ctrl_ = dp->bound_ctrl;
  }
  src0.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  vsrc1.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
}

void VCmpxClassF64Vopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t dpp_old_vcc_ = wf.vcc();
  uint64_t dpp_write_mask_ = ~0ULL;
  if (inst_.src0 == amdgpu::SRC_DPP) {
    dpp_write_mask_ = 0;
    for (uint32_t ln = 0; ln < wf.wf_size(); ++ln) {
      uint32_t row = ln / 16;
      uint32_t bank = (ln % 16) / 4;
      if ((dpp_row_mask_ & (1u << row)) && (dpp_bank_mask_ & (1u << bank)))
        dpp_write_mask_ |= (1ULL << ln);
    }
  }
  if (inst_.src0 == amdgpu::SRC_DPP)
    amdgpu::dpp::apply_dpp(src_operands_[0], dpp_ctrl_, dpp_row_mask_, dpp_bank_mask_,
                           dpp_bound_ctrl_, dpp_src0_, wf);
  if (inst_.src0 == amdgpu::SRC_SDWA) {
    auto &cu = wf.cu();
    uint32_t ws = wf.wf_size();
    if (sdwa_src0_sel_ != amdgpu::sdwa::DWORD) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[0]->encoding_value_;
      uint32_t result[64];
      for (uint32_t i = 0; i < ws; ++i)
        result[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src0_sel_, sdwa_src0_sext_);
      if (sdwa_src0_abs_ || sdwa_src0_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result[i]);
          if (sdwa_src0_abs_)
            sv = std::fabs(sv);
          if (sdwa_src0_neg_)
            sv = -sv;
          result[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src0_ = std::make_unique<DppOperand>(*src_operands_[0], result, static_cast<int>(ws));
      src_operands_[0] = dpp_src0_.get();
    }
    if (sdwa_src1_sel_ != amdgpu::sdwa::DWORD && num_src_ > 1) {
      uint32_t vb = wf.vgpr_alloc().base + src_operands_[1]->encoding_value_;
      uint32_t result1[64];
      for (uint32_t i = 0; i < ws; ++i)
        result1[i] =
            amdgpu::sdwa::sdwa_src_select(cu.read_vgpr(vb, i), sdwa_src1_sel_, sdwa_src1_sext_);
      if (sdwa_src1_abs_ || sdwa_src1_neg_) {
        for (uint32_t i = 0; i < ws; ++i) {
          float sv = std::bit_cast<float>(result1[i]);
          if (sdwa_src1_abs_)
            sv = std::fabs(sv);
          if (sdwa_src1_neg_)
            sv = -sv;
          result1[i] = std::bit_cast<uint32_t>(sv);
        }
      }
      dpp_src1_ = std::make_unique<DppOperand>(*src_operands_[1], result1, static_cast<int>(ws));
      src_operands_[1] = dpp_src1_.get();
    }
  }
  if (dpp_src0_)
    src0.set_delegate(dpp_src0_.get());
  if (dpp_src1_)
    vsrc1.set_delegate(dpp_src1_.get());
  uint64_t exec = wf.exec();
  uint64_t result = 0;
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    double s0 = std::bit_cast<double>(src0.read_lane64(wf, lane));
    uint32_t mask = vsrc1.read_lane(wf, lane);
    bool match = false;
    if ((mask & 0x001) && std::isnan(s0) &&
        (std::bit_cast<uint64_t>(s0) & 0x0008000000000000ULL) == 0)
      match = true;
    if ((mask & 0x002) && std::isnan(s0) &&
        (std::bit_cast<uint64_t>(s0) & 0x0008000000000000ULL) != 0)
      match = true;
    if ((mask & 0x004) && std::isinf(s0) && s0 < 0)
      match = true;
    if ((mask & 0x008) && std::isnormal(s0) && s0 < 0)
      match = true;
    if ((mask & 0x010) && !std::isnormal(s0) && !std::isinf(s0) && !std::isnan(s0) && s0 != 0.0 &&
        std::signbit(s0))
      match = true;
    if ((mask & 0x020) && s0 == 0.0 && std::signbit(s0))
      match = true;
    if ((mask & 0x040) && s0 == 0.0 && !std::signbit(s0))
      match = true;
    if ((mask & 0x080) && !std::isnormal(s0) && !std::isinf(s0) && !std::isnan(s0) && s0 != 0.0 &&
        !std::signbit(s0))
      match = true;
    if ((mask & 0x100) && std::isnormal(s0) && s0 > 0)
      match = true;
    if ((mask & 0x200) && std::isinf(s0) && s0 > 0)
      match = true;
    if (match)
      result |= (1ULL << lane);
  }
  wf.set_exec(result);
  if (inst_.src0 == amdgpu::SRC_DPP && dpp_write_mask_ != ~0ULL) {
    uint64_t new_vcc = wf.vcc();
    uint64_t merged = (new_vcc & dpp_write_mask_) | (dpp_old_vcc_ & ~dpp_write_mask_);
    wf.set_vcc(merged);
  }
  if (inst_.src0 == amdgpu::SRC_SDWA && sdwa_sd_) {
    uint64_t cmp_result = wf.vcc();
    uint32_t sb = wf.sgpr_alloc().base;
    wf.cu().write_sgpr(sb + sdwa_sdst_, static_cast<uint32_t>(cmp_result));
    wf.cu().write_sgpr(sb + sdwa_sdst_ + 1, static_cast<uint32_t>(cmp_result >> 32));
    wf.set_vcc(dpp_old_vcc_);
  }
  src0.clear_delegate();
  vsrc1.clear_delegate();
}

} // namespace gfx1250
} // namespace rocjitsu
