// Copyright (c) 2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/gfx1250/vopd.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <format>
#include <string>

namespace rocjitsu {
namespace gfx1250 {

namespace {

Operand make_src0(uint32_t bits, bool vopd3, bool use_literal, uint32_t literal, uint16_t encoded) {
  if (use_literal && encoded == 255)
    return Operand(bits, OperandType::OPR_SIMM32, static_cast<int>(literal));
  return Operand(bits, vopd3 ? OperandType::OPR_SRC_SIMPLE : OperandType::OPR_SRC, encoded);
}

std::string operand_list(const Operand &dst, const Operand &src0, const Operand &src1) {
  return dst.name() + ", " + src0.name() + ", " + src1.name();
}

} // namespace

bool Vopd::is_vopd(const MachineInst *inst) {
  uint32_t word0 = *reinterpret_cast<const uint32_t *>(inst);
  return (word0 >> 24) == 0xCF || (word0 >> 26) == 0x32;
}

const char *Vopd::op_name(uint16_t op) {
  switch (op) {
  case 0:
    return "v_dual_fmac_f32";
  case 1:
    return "v_dual_fmaak_f32";
  case 2:
    return "v_dual_fmamk_f32";
  case 3:
    return "v_dual_mul_f32";
  case 4:
    return "v_dual_add_f32";
  case 5:
    return "v_dual_sub_f32";
  case 6:
    return "v_dual_subrev_f32";
  case 7:
    return "v_dual_mul_dx9_zero_f32";
  case 8:
    return "v_dual_mov_b32";
  case 9:
    return "v_dual_cndmask_b32";
  case 10:
    return "v_dual_max_num_f32";
  case 11:
    return "v_dual_min_num_f32";
  case 16:
    return "v_dual_add_nc_u32";
  case 17:
    return "v_dual_lshlrev_b32";
  case 18:
    return "v_dual_bitop2_b32";
  case 19:
    return "v_dual_fma_f32";
  case 20:
    return "v_dual_sub_nc_u32";
  case 21:
    return "v_dual_lshrrev_b32";
  case 22:
    return "v_dual_ashrrev_i32";
  case 23:
    return "v_dual_max_i32";
  case 24:
    return "v_dual_min_i32";
  case 32:
    return "v_dual_add_f64";
  case 33:
    return "v_dual_mul_f64";
  case 34:
    return "v_dual_min_num_f64";
  case 35:
    return "v_dual_max_num_f64";
  case 36:
    return "v_dual_fmac_f64";
  default:
    return "v_dual_unknown";
  }
}

bool Vopd::is_float32_op(uint16_t op) {
  switch (op) {
  case 0:
  case 1:
  case 2:
  case 3:
  case 4:
  case 5:
  case 6:
  case 7:
  case 10:
  case 11:
  case 19:
    return true;
  default:
    return false;
  }
}

uint32_t Vopd::apply_neg(uint32_t value, uint8_t neg_bits, uint8_t src_idx) {
  return (neg_bits & (1u << src_idx)) ? (value ^ 0x80000000u) : value;
}

uint32_t Vopd::bitop2(uint32_t src0, uint32_t src1, uint32_t truth_table) {
  uint32_t result = 0;
  for (uint32_t bit = 0; bit < 32; ++bit) {
    uint32_t idx = (((src0 >> bit) & 1u) << 2) | (((src1 >> bit) & 1u) << 1);
    result |= ((truth_table >> idx) & 1u) << bit;
  }
  return result;
}

uint32_t Vopd::execute_slot(const Slot &slot, amdgpu::Wavefront &wf, uint32_t lane) {
  uint32_t src0 = slot.src0->read_lane(wf, lane);
  uint32_t src1 = slot.src1->read_lane(wf, lane);
  uint32_t src2 = slot.has_src2_operand ? slot.src2->read_lane(wf, lane) : slot.src2_imm;
  if (is_float32_op(slot.op)) {
    src0 = apply_neg(src0, slot.neg, 0);
    src1 = apply_neg(src1, slot.neg, 1);
    src2 = apply_neg(src2, slot.neg, 2);
  }

  switch (slot.op) {
  case 0: {
    float result = std::fma(std::bit_cast<float>(src0), std::bit_cast<float>(src1),
                            std::bit_cast<float>(slot.dst->read_lane(wf, lane)));
    return std::bit_cast<uint32_t>(result);
  }
  case 1: {
    float result = std::fma(std::bit_cast<float>(src0), std::bit_cast<float>(src1),
                            std::bit_cast<float>(src2));
    return std::bit_cast<uint32_t>(result);
  }
  case 2: {
    float result = std::fma(std::bit_cast<float>(src0), std::bit_cast<float>(src2),
                            std::bit_cast<float>(src1));
    return std::bit_cast<uint32_t>(result);
  }
  case 3: {
    float result = std::bit_cast<float>(src0) * std::bit_cast<float>(src1);
    return std::bit_cast<uint32_t>(result);
  }
  case 7: {
    float lhs = std::bit_cast<float>(src0);
    float rhs = std::bit_cast<float>(src1);
    if (lhs == 0.0f || rhs == 0.0f)
      return std::bit_cast<uint32_t>(0.0f);
    return std::bit_cast<uint32_t>(lhs * rhs);
  }
  case 4: {
    float result = std::bit_cast<float>(src0) + std::bit_cast<float>(src1);
    return std::bit_cast<uint32_t>(result);
  }
  case 5: {
    float result = std::bit_cast<float>(src0) - std::bit_cast<float>(src1);
    return std::bit_cast<uint32_t>(result);
  }
  case 6: {
    float result = std::bit_cast<float>(src1) - std::bit_cast<float>(src0);
    return std::bit_cast<uint32_t>(result);
  }
  case 8:
    return src0;
  case 9: {
    uint64_t condition = slot.uses_vcc ? wf.vcc() : slot.src2->read_scalar64(wf);
    return ((condition >> lane) & 1u) ? src1 : src0;
  }
  case 10: {
    float result = std::fmax(std::bit_cast<float>(src0), std::bit_cast<float>(src1));
    return std::bit_cast<uint32_t>(result);
  }
  case 11: {
    float result = std::fmin(std::bit_cast<float>(src0), std::bit_cast<float>(src1));
    return std::bit_cast<uint32_t>(result);
  }
  case 16:
    return src0 + src1;
  case 17:
    return src1 << (src0 & 31u);
  case 18:
    return bitop2(src0, src1, slot.src2_imm);
  case 19: {
    float result = std::fma(std::bit_cast<float>(src0), std::bit_cast<float>(src1),
                            std::bit_cast<float>(src2));
    return std::bit_cast<uint32_t>(result);
  }
  case 20:
    return src0 - src1;
  case 21:
    return src1 >> (src0 & 31u);
  case 22:
    return static_cast<uint32_t>(static_cast<int32_t>(src1) >> (src0 & 31u));
  case 23:
    return static_cast<uint32_t>(std::max(static_cast<int32_t>(src0), static_cast<int32_t>(src1)));
  case 24:
    return static_cast<uint32_t>(std::min(static_cast<int32_t>(src0), static_cast<int32_t>(src1)));
  default:
    throw util::UnimplementedInst(op_name(slot.op));
  }
}

Vopd::Vopd(const MachineInst *inst)
    : IsaInstruction<Isa>("vopd", make_exec_fn<Vopd>()), dstx_(32, OperandType::OPR_VGPR, 0),
      dsty_(32, OperandType::OPR_VGPR, 0), srcx0_(32, OperandType::OPR_SRC, 0),
      srcx1_(32, OperandType::OPR_VGPR, 0), srcx2_(32, OperandType::OPR_VGPR, 0),
      srcy0_(32, OperandType::OPR_SRC, 0), srcy1_(32, OperandType::OPR_VGPR, 0),
      srcy2_(32, OperandType::OPR_VGPR, 0) {
  const auto *words = reinterpret_cast<const uint32_t *>(inst);
  raw_encoding_ = words;
  word0_ = words[0];
  word1_ = words[1];

  if ((word0_ >> 24) == 0xCF) {
    format_ = Format::Vopd3;
    size_ = 12;
    encoding_id_ = 0xCF;
    word2_ = words[2];
    opx_ = static_cast<uint16_t>((word0_ >> 18) & 0x3F);
    opy_ = static_cast<uint16_t>((word0_ >> 12) & 0x3F);
    uint16_t srcx0 = static_cast<uint16_t>(word0_ & 0x1FF);
    uint16_t srcy0 = static_cast<uint16_t>(word1_ & 0x1FF);
    negx_ = static_cast<uint8_t>((word1_ >> 9) & 0x7);
    negy_ = static_cast<uint8_t>((word1_ >> 12) & 0x7);
    uint16_t vsrcx1 = static_cast<uint16_t>((word1_ >> 16) & 0xFF);
    uint16_t vsrcx2 = static_cast<uint16_t>((word1_ >> 24) & 0xFF);
    uint16_t vdstx = static_cast<uint16_t>(word2_ & 0xFF);
    uint16_t vsrcy1 = static_cast<uint16_t>((word2_ >> 8) & 0xFF);
    uint16_t vsrcy2 = static_cast<uint16_t>((word2_ >> 16) & 0xFF);
    uint16_t vdsty = static_cast<uint16_t>((word2_ >> 24) & 0xFF);

    dstx_ = Operand(32, OperandType::OPR_VGPR, vdstx);
    dsty_ = Operand(32, OperandType::OPR_VGPR, vdsty);
    srcx0_ = make_src0(32, true, false, 0, srcx0);
    srcy0_ = make_src0(32, true, false, 0, srcy0);
    srcx1_ = Operand(32, OperandType::OPR_VGPR, vsrcx1);
    srcy1_ = Operand(32, OperandType::OPR_VGPR, vsrcy1);
    srcx2_ = (opx_ == 9) ? Operand(64, OperandType::OPR_SREG, vsrcx2)
                         : Operand(32, OperandType::OPR_VGPR, vsrcx2);
    srcy2_ = (opy_ == 9) ? Operand(64, OperandType::OPR_SREG, vsrcy2)
                         : Operand(32, OperandType::OPR_VGPR, vsrcy2);
  } else {
    format_ = Format::VopdXy;
    encoding_id_ = 0x32;
    opx_ = static_cast<uint16_t>((word0_ >> 22) & 0xF);
    opy_ = static_cast<uint16_t>((word0_ >> 17) & 0x1F);
    uint16_t srcx0 = static_cast<uint16_t>(word0_ & 0x1FF);
    uint16_t vsrcx1 = static_cast<uint16_t>((word0_ >> 9) & 0xFF);
    uint16_t srcy0 = static_cast<uint16_t>(word1_ & 0x1FF);
    uint16_t vsrcy1 = static_cast<uint16_t>((word1_ >> 9) & 0xFF);
    uint16_t vdstx = static_cast<uint16_t>((word1_ >> 24) & 0xFF);
    uint16_t vdsty_hi = static_cast<uint16_t>((word1_ >> 17) & 0x7F);
    uint16_t vdsty = static_cast<uint16_t>((vdsty_hi << 1) | ((~vdstx) & 1u));
    has_literal_ = srcx0 == 255 || srcy0 == 255 || opx_ == 1 || opx_ == 2 || opy_ == 1 || opy_ == 2;
    size_ = has_literal_ ? 12 : 8;
    if (has_literal_) {
      word2_ = words[2];
      literal_ = word2_;
    }

    dstx_ = Operand(32, OperandType::OPR_VGPR, vdstx);
    dsty_ = Operand(32, OperandType::OPR_VGPR, vdsty);
    srcx0_ = make_src0(32, false, has_literal_, literal_, srcx0);
    srcy0_ = make_src0(32, false, has_literal_, literal_, srcy0);
    srcx1_ = Operand(32, OperandType::OPR_VGPR, vsrcx1);
    srcy1_ = Operand(32, OperandType::OPR_VGPR, vsrcy1);
  }

  dstx_.set_vgpr_msb_role(amdgpu::VgprMsbRole::Dst);
  dsty_.set_vgpr_msb_role(amdgpu::VgprMsbRole::Dst);
  srcx0_.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  srcy0_.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src0);
  srcx1_.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
  srcy1_.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src1);
  srcx2_.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src2);
  srcy2_.set_vgpr_msb_role(amdgpu::VgprMsbRole::Src2);

  opcode_ = static_cast<uint16_t>((opx_ << 8) | opy_);
  init_operands();
  mnemonic_storage_ = std::string(op_name(opx_)) + " :: " + op_name(opy_);
  mnemonic_ = mnemonic_storage_;
  disassembly_ = format_slot(x_) + " :: " + format_slot(y_);
}

void Vopd::init_operands() {
  const bool vopd3 = format_ == Format::Vopd3;
  x_ = Slot{opx_, &dstx_, &srcx0_, &srcx1_, &srcx2_, 0, negx_, false, false, false};
  y_ = Slot{opy_, &dsty_, &srcy0_, &srcy1_, &srcy2_, 0, negy_, false, false, false};

  if (vopd3) {
    x_.has_src2_operand = opx_ == 9 || opx_ == 19;
    y_.has_src2_operand = opy_ == 9 || opy_ == 19;
    x_.src2_is_imm = opx_ == 18;
    y_.src2_is_imm = opy_ == 18;
    x_.src2_imm = static_cast<uint32_t>(srcx2_.encoding_value());
    y_.src2_imm = static_cast<uint32_t>(srcy2_.encoding_value());
  } else {
    x_.uses_vcc = opx_ == 9;
    y_.uses_vcc = opy_ == 9;
    if (opx_ == 1 || opx_ == 2) {
      x_.src2_is_imm = true;
      x_.src2_imm = literal_;
    }
    if (opy_ == 1 || opy_ == 2) {
      y_.src2_is_imm = true;
      y_.src2_imm = literal_;
    }
  }

  dst_operands_[0] = &dstx_;
  dst_operands_[1] = &dsty_;
  src_operands_[0] = &srcx0_;
  src_operands_[1] = &srcx1_;
  src_operands_[2] = &srcy0_;
  src_operands_[3] = &srcy1_;
  num_dst_ = 2;
  num_src_ = 4;
}

std::string Vopd::format_slot(const Slot &slot) const {
  std::string out = op_name(slot.op);
  out += " ";
  switch (slot.op) {
  case 8:
    out += slot.dst->name() + ", " + slot.src0->name();
    break;
  case 9:
    out += operand_list(*slot.dst, *slot.src0, *slot.src1);
    if (!slot.uses_vcc)
      out += ", " + slot.src2->name();
    break;
  case 18:
    out += operand_list(*slot.dst, *slot.src0, *slot.src1);
    out += std::format(" bitop3:0x{:02x}", slot.src2_imm & 0xFF);
    break;
  case 19:
    out += operand_list(*slot.dst, *slot.src0, *slot.src1) + ", " + slot.src2->name();
    break;
  case 1:
    out += operand_list(*slot.dst, *slot.src0, *slot.src1);
    out += std::format(", 0x{:08x}", slot.src2_imm);
    break;
  case 2:
    out += slot.dst->name() + ", " + slot.src0->name();
    out += std::format(", 0x{:08x}, ", slot.src2_imm);
    out += slot.src1->name();
    break;
  default:
    out += operand_list(*slot.dst, *slot.src0, *slot.src1);
    break;
  }
  return out;
}

void Vopd::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t exec = wf.exec();
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t x_result = execute_slot(x_, wf, lane);
    uint32_t y_result = execute_slot(y_, wf, lane);
    x_.dst->write_lane(wf, lane, x_result);
    y_.dst->write_lane(wf, lane, y_result);
  }
}

} // namespace gfx1250
} // namespace rocjitsu
